[IV-23-24] Objetivo 2: Modelización del problema a resolver.
migueruiz/Automatricula pull request #11
Opened 2023-10-10 11:05 UTC by johnwaves

Sobre la estructura del repositorio:

* [ ] ¿He seguido las mejores prácticas en el nombre de las clases y ficheros y
   disposición de los mismos?
* [ ] ¿He mirado tanto reglas generales (para cualquier repo) como reglas
específicas para el lenguaje con el que se está trabajando?

Sobre el planteamiento:

* [ ] ¿Se han planteado una serie de issues, asignados a las historias de
usuario pertinentes, que clarifiquen qué es lo que necesitan los usuarios e
identifiquen las diferentes partes del problema?
* [ ] ¿Los issues representan un problema, y no una tarea?

Sobre el análisis del problema:

* [ ] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [ ] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [ ] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?.

Sobre el código:

* [ ] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [ ] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [ ] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [ ] ¿Todos los issues creados están relacionados con a una HU?
* [ ] ¿Ha asignado el propietario/la propietaria del repositorio todos los
issues planteados al *milestone* correspondiente?
* [ ] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit?
* [ ] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [ ] ¿Es el milestone sobre el que estoy trabajando un producto
   mínimamente viable? ¿O tengo que solicitar al product manager que precise de
   qué producto se trata?
* [ ] ¿Se ha comprobado que el código entregado sea sintácticamente
correcto?

Lista de comprobación para el propietario/a del repositorio:

* [ ] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [ ] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [ ] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [ ] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [ ] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [ ] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [ ] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?

2023-10-10 11:06 UTC, johnwaves commented
@migueruiz, cuando puedas añade el PR a un milestone y asígnale la etiqueta hacktoberfest-accepted, gracias! 😉

2023-10-13 10:52 UTC, migueruiz commented
Perdona por la tardanza he tenido una serie de problemas familiares...; podrías por favor detallarme a que te refieres, lo siento pero no he entendido tu mensaje.

2023-10-14 17:28 UTC, johnwaves commented
> @johnwaves Perdona por la tardanza he tenido una serie de problemas familiares...; podrías por favor detallarme a que te refieres, lo siento pero no he entendido tu mensaje.

No te preocupes. Para el Objetivo 2 debes asignar a este Pull Request un milestone, en este caso, el M0. Eso se hace en el panel derecho de esta página, donde aparece la opción Milestone (o Htito si lo tienes en español).

Lo otro que te comenté es para el Hacktoberfest, algo opcional, pero que estaría interesante participar. Para ello debes crear una nueva etiqueta que ponga "hacktoberfest-accepted" y asignarla a este PR también. Es también en el apartado derecho de esta página, en el apartado Labels si lo tienes en inglés.

2023-10-16 08:10 UTC, migueruiz commented
De acuerdo, ya lo he hecho, gracias!!

2023-10-23 00:10 UTC, johnwaves commented
@migueruiz ya he añadido el código. Échale un vistazo a los nuevos issues, salvo el del solapamiento de horarios, los demás creo que sí que pertenecen todos al M0. Ve completando cuando puedas la lista de comprobación para el propietario del repositorio y la mandas como un comentario por aquí cuando apruebes los cambios. Gracias de antemano 😁.

2023-10-23 13:27 UTC, migueruiz commented
Lista de comprobación para el propietario/a del repositorio:

* [ ] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [ ] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [ ] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [ ] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [ ] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [ ] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [ ] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?

2023-10-23 13:28 UTC, migueruiz commented
Hola @johnwaves, yo lo veo todo correcto, ya estaría en mano del profesor, así que quedaría que modificases el comentario inicial del PR para que no aparezca los comentarios del propietario, y que subas el enlace en el repositorio del objetivo. Muchas gracias por tu trabajo. 😄

2023-10-23 13:29 UTC, migueruiz approved these changes

2023-10-23 17:15 UTC, JJ commented
En el mensaje de aprobación deberías seguir la lista de comprobación e incluirla, por favor. Lo puedes hacer ahora en un comentario, si quieres.

2023-10-23 17:17 UTC, JJ commented
Además. tiene también 4 revisores asignados. Por favor, avisadme cuando uno o preferiblemente dos aprueben también o cuando pasen dos o tres días.

2023-10-23 17:19 UTC, migueruiz commented
> Lista de comprobación para el propietario/a del repositorio:
> 
> * [x]  ¿Los issues que ha planteado la persona son efectivamente problemas y
>   evidencian comprensión de las historias de usuario? Si no es así, es mejor que
>   se le transmita antes de que empiece a crear cualquier código erróneo.
> * [x]  ¿Has comprobado que efectivamente el compañero/a ha seguido _su_ lista de
>   comprobación?
> * [x]  ¿El código creado es una modelización válida de las historias de usuario
>   creadas por ti, y te sirve como base para programar la lógica de negocio?
> * [x]  ¿El código creado sigue las mejores prácticas para el lenguaje de
>   programación que hayáis consensuado, tanto en identificadores, como
>   nombres de ficheros, como disposición de los diferentes ficheros en el
>   repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
>   aportan código para resolver el problema planteado en el mismo?
> * [x]  ¿He comprobado que el código compile, o que quien lo ha programado ha lo
>   ha hecho y documentado en el repositorio?
> * [x]  ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
>   correspondiente, que será el primero?
> * [x]  ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
>   el objetivo 4 para poder programar la lógica de negocio?

2023-10-23 17:19 UTC, migueruiz commented
Lista de comprobación para el propietario/a del repositorio:

* [x] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [x] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [x] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [x] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [x] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [x] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?

2023-10-25 09:41 UTC, LuciaAnsino requested changes

2023-10-25 09:41 UTC, LuciaAnsino commented on src/types.ts
> +        nombre: string;
¿En asignaturas no debería de contener un dato del tipo Asignatura, definida en asignatura.ts?

2023-10-25 16:56 UTC, johnwaves commented on src/types.ts
> +        nombre: string;
La idea para ese type es que obtenga los datos de las asignaturas que el estudiante tiene matriculadas, por tanto, los objetos de tipo Asignatura se encuentran en el array de asignaturas de una instancia de Estudiante. He corregido un fallo en el diseño del código, espero que se entienda mejor ahora 😅.

2023-10-26 08:24 UTC, LuciaAnsino requested changes

2023-10-26 08:24 UTC, LuciaAnsino commented on src/curso.ts
> +export class Curso{
En la modelización no deberías poner métodos de la clase. Eso es requerido en otros milestone.

2023-10-26 08:24 UTC, LuciaAnsino commented on src/estudiante.ts
> +export class Estudiante{
Igusal que en la clase anterior, no debes poner métodos de la clase, ya que no es necesario para la modelización.

2023-10-26 08:24 UTC, LuciaAnsino commented on src/horario.ts
> +export class Horario{
En esta clase pasa lo mismo con los métodos.

2023-10-26 20:54 UTC, johnwaves commented on src/curso.ts
> +export class Curso{
De acuerdo. He dejado solo los getters. ¡Gracias 😁!

2023-10-26 20:54 UTC, johnwaves commented on src/estudiante.ts
> +export class Estudiante{
Aquí también los he eliminado.

2023-10-26 20:54 UTC, johnwaves commented on src/horario.ts
> +export class Horario{
Y aquí también.

2023-10-28 10:51 UTC, johnwaves commented
@JJ Listo para revisión!

2023-10-30 07:46 UTC, JJ requested changes
Gracias a @LuciaAnsino y a @migueruiz por la interacción.
El problema principal es que no se han seguido las mejores prácticas en el desarrollo. En muchos casos los issues no plantean el problema, pero incluso en el caso en el que lo hacen, no se ha tratado de resolver con un código mínimo. Habría que empezar desde cero en muchos casos, reformulando issues y reescribiendo el código, usando en los commits que lo incluyan las buenas prácticas habituales.

2023-10-30 07:46 UTC, JJ commented on iv.yaml
> +  - src/curso.ts
Sólo se pide que incluyas una.

2023-10-30 07:46 UTC, JJ commented on iv.yaml
> +  - src/estudiante.ts
Si lo incluyes, por favor, asegúrate que *es* una entidad. ¿`estudiante`  lo es?

2023-10-30 07:46 UTC, JJ commented on src/curso.ts
> +    public getGrupo(nombre_grupo: string): Grupo | undefined{
En [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-2.md#sobre-el-c%C3%B3digo-definido) se menciona:

> El interfaz debe reflejar las necesidades de la lógica de negocio, y no la implementación. Exponer con un get todos las variables de instancia hay que justificarlo, no hacerlo sistemáticamente.

pero también:

> ólo hay que incluir en el código lo que sea necesario para entender el modelo. Los setters, y mucho menos los getters, en general no van a ser necesarios.

2023-10-30 07:46 UTC, JJ commented on src/curso.ts
> +export class Curso{
Los getters también son métodos de clase.

2023-10-30 07:46 UTC, JJ commented on src/curso.ts
> +export class Curso{
Esta clase se crea en el commit https://github.com/migueruiz/Automatricula/commit/f562048f64b79fe4ca75a64c6a20cb3e0dc389ac, cuyo mensaje no sigue las mejores prácticas, y no aporta ninguna información ni razón a lo que se ha hecho, y además menciona dos issues, #16 y #17. El #17 no tiene nada que ver con el Curso, además. Los commits deben ser atómicos, y justificar las elecciones que se hacen.

2023-10-30 07:46 UTC, JJ commented on src/curso.ts
> +    public getNombre(): string{
¿Qué es el nombre del curso?

2023-10-30 07:46 UTC, JJ commented on src/estudiante.ts
> +        this.dni = dni;
¿Qué parte de la lógica de negocio necesita el DNI?

2023-10-30 07:46 UTC, JJ commented on src/estudiante.ts
> +    private correo: string;
Esto se ha creado completo en el commit https://github.com/migueruiz/Automatricula/commit/be80691f8264019806bfc65571d608a9135f83a4 que, una vez más, no sigue las buenas prácticas. "Definida clase" no aporta ninguna información sobre las decisiones tomadas.

2023-10-30 07:46 UTC, JJ commented on src/horario.ts
> +export class Horario{
Esto es el resultado de la lógica de negocio. Como tal, no hace falta estrictamente que se modele. Pero si se modela, debe hacerse bien, teniendo en cuenta que, por ejemplo, el estudiante del que se trate se conocerá ya.

2023-10-30 07:46 UTC, JJ commented on src/horario.ts
> +    private estudiante: Estudiante;
¿Cada horario va a almacenar completa la estructura de datos del estudiante?

2023-10-30 07:46 UTC, JJ commented on src/types.ts
> +        nombre: string;
Se tienen que resolver todos los comentarios.

2023-10-30 10:48 UTC, LuciaAnsino approved these changes

2023-11-02 16:14 UTC, JJ commented on src/asignatura.ts
> + * Clase Asignatura.
Antes de que continúes, por favor ten en cuenta que commits como este https://github.com/migueruiz/Automatricula/commit/786915d33a38dab29f9828cec54d4b1a00168df0 no siguen las buenas prácticas recomendadas. Ni siquiera hace lo que dice, crear una clase, pero es que si lo hiciera, debería de explicar la decisión,

2023-11-02 16:24 UTC, johnwaves commented on src/asignatura.ts
> + * Clase Asignatura.
No he visto este comentario antes de seguir 🤦‍♂️.

2023-11-02 16:26 UTC, johnwaves commented on src/asignatura.ts
> + * Clase Asignatura.
> Antes de que continúes, por favor ten en cuenta que commits como este [786915d](https://github.com/migueruiz/Automatricula/commit/786915d33a38dab29f9828cec54d4b1a00168df0) no siguen las buenas prácticas recomendadas. Ni siquiera hace lo que dice, crear una clase, pero es que si lo hiciera, debería de explicar la decisión,

¿Se podría explicar la decisión de alguna forma después?

2023-11-02 16:35 UTC, migueruiz commented
Hola @johnwaves, he visto que has solicitado que haga review, antes de nada te quería comentar, que resolvieses todos los comentarios antes de todo, ya que sino presentaría problemas!!

2023-11-02 16:35 UTC, migueruiz approved these changes
Lista de comprobación para el propietario/a del repositorio:

* [x] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [x] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [x] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [x] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [x] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [x] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?

Muchas gracias por tu trabajo!!

2023-11-02 16:44 UTC, johnwaves commented
> Gracias a @LuciaAnsino y a @migueruiz por la interacción. El problema principal es que no se han seguido las mejores prácticas en el desarrollo. En muchos casos los issues no plantean el problema, pero incluso en el caso en el que lo hacen, no se ha tratado de resolver con un código mínimo. Habría que empezar desde cero en muchos casos, reformulando issues y reescribiendo el código, usando en los commits que lo incluyan las buenas prácticas habituales.

He empezado de nuevo planteando los issues y reorganizando el código de acuerdo con sus comentarios.

2023-11-02 16:45 UTC, johnwaves commented on iv.yaml
> +  - src/curso.ts
Solucionado

2023-11-02 16:45 UTC, johnwaves commented on src/curso.ts
> +    public getGrupo(nombre_grupo: string): Grupo | undefined{
He actualizado el código y ya no se incluyen.

2023-11-02 16:47 UTC, johnwaves commented on src/estudiante.ts
> +        this.dni = dni;
Es cierto que no se necesita por ahora.

2023-11-02 16:48 UTC, johnwaves commented on src/curso.ts
> +    public getNombre(): string{
Es la forma de identificarlo (primero, segundo, etc).

2023-11-02 16:49 UTC, johnwaves commented on src/horario.ts
> +    private estudiante: Estudiante;
Ya se encuentra solucionado. Es verdad que no hacía ni hace falta por el momento.

2023-11-02 16:50 UTC, johnwaves commented on iv.yaml
> +  - src/estudiante.ts
No lo es. Ya está solucionado 😁.

2023-11-02 16:50 UTC, johnwaves commented
> Hola @johnwaves, he visto que has solicitado que haga review, antes de nada te quería comentar, que resolvieses todos los comentarios antes de todo, ya que sino presentaría problemas!!

¡Listo! 😉

2023-11-03 08:06 UTC, JJ requested changes
Para este y cualquier otro modelo, es conveniente que hagas un "paseo" por lo que tendría que hacer @migueruiz en el objetivo 4, a ver qué tenemos, partiendo claro está de la #3 (o cualquier otra).

1. Un estudiante quiere matricularse en un número determinado de asignaturas. ¿Tenemos esa "petición" o "deseo"?
2. La lógica de negocio examina esa petición, devolviendo ¿qué exactamente? ¿Las asignaturas que no se solapan? ¿Una combinación de asignaturas que no se solapan? ¿Todas las combinaciones de asignaturas que no se solapan? 
3. ¿Cómo se hace lo anterior? ¿Todas las asignaturas a la vez? ¿Primero las asignaturas que son "imprescindibles" (¿pide eso la lógica de negocio?)? ¿Luego las asignaturas una a una y se te dice *para cada una* si puedes matricularte o no?

2 y 3 no son compatibles, o lo haces de una forma o de otra, pero una de las formas puede ser más simple y otra más compleja y por eso hay que empezar siempre por la más simple.

En todo caso, siempre hay que mirar al problema globalmente y no palabra por palabra (como "asignatura" u "horario" que se encuentre en la HU), porque se trata de hacer un modelo. En todo caso conviene revisar los issues a ver si realmente constituyen problemas a resolver, y no "clase esto" o "Qué es x" porque de esa forma, por el Problema XY que comenté en clase, no se resuelve el problema.

2023-11-04 12:05 UTC, johnwaves commented
> Para este y cualquier otro modelo, es conveniente que hagas un "paseo" por lo que tendría que hacer @migueruiz en el objetivo 4, a ver qué tenemos, partiendo claro está de la #3 (o cualquier otra).
> 
> 1. Un estudiante quiere matricularse en un número determinado de asignaturas. ¿Tenemos esa "petición" o "deseo"?
> 2. La lógica de negocio examina esa petición, devolviendo ¿qué exactamente? ¿Las asignaturas que no se solapan? ¿Una combinación de asignaturas que no se solapan? ¿Todas las combinaciones de asignaturas que no se solapan?
> 3. ¿Cómo se hace lo anterior? ¿Todas las asignaturas a la vez? ¿Primero las asignaturas que son "imprescindibles" (¿pide eso la lógica de negocio?)? ¿Luego las asignaturas una a una y se te dice _para cada una_ si puedes matricularte o no?
> 
> 2 y 3 no son compatibles, o lo haces de una forma o de otra, pero una de las formas puede ser más simple y otra más compleja y por eso hay que empezar siempre por la más simple.
> 
> En todo caso, siempre hay que mirar al problema globalmente y no palabra por palabra (como "asignatura" u "horario" que se encuentre en la HU), porque se trata de hacer un modelo. En todo caso conviene revisar los issues a ver si realmente constituyen problemas a resolver, y no "clase esto" o "Qué es x" porque de esa forma, por el Problema XY que comenté en clase, no se resuelve el problema.



> Para este y cualquier otro modelo, es conveniente que hagas un "paseo" por lo que tendría que hacer @migueruiz en el objetivo 4, a ver qué tenemos, partiendo claro está de la #3 (o cualquier otra).
> 
> 1. Un estudiante quiere matricularse en un número determinado de asignaturas. ¿Tenemos esa "petición" o "deseo"?
> 2. La lógica de negocio examina esa petición, devolviendo ¿qué exactamente? ¿Las asignaturas que no se solapan? ¿Una combinación de asignaturas que no se solapan? ¿Todas las combinaciones de asignaturas que no se solapan?
> 3. ¿Cómo se hace lo anterior? ¿Todas las asignaturas a la vez? ¿Primero las asignaturas que son "imprescindibles" (¿pide eso la lógica de negocio?)? ¿Luego las asignaturas una a una y se te dice _para cada una_ si puedes matricularte o no?
> 
> 2 y 3 no son compatibles, o lo haces de una forma o de otra, pero una de las formas puede ser más simple y otra más compleja y por eso hay que empezar siempre por la más simple.
> 
> En todo caso, siempre hay que mirar al problema globalmente y no palabra por palabra (como "asignatura" u "horario" que se encuentre en la HU), porque se trata de hacer un modelo. En todo caso conviene revisar los issues a ver si realmente constituyen problemas a resolver, y no "clase esto" o "Qué es x" porque de esa forma, por el Problema XY que comenté en clase, no se resuelve el problema.

Haciendo el recuento de lo que ya hay hecho:

1. La matriculación, entendiéndose como elección de asignaturas nuevas, no se contempla en las historias de usuario. El usuario parte desde el punto en el que ya tiene unas asignaturas matriculadas y lo que desea es cambiar de grupo en caso de solapamiento de horarios.
2. En primer lugar, y según #3, la lógica de negocio contempla la visualización del horario conjunto de todas las asignaturas. Una vez obtenido, debería proponer una alternativa en caso de solapamiento de asignaturas.
3.  La alternativa del punto anterior se deberá tratar como lógica de negocio a seguir en el milestone 2.

Llegados a este punto, no sé cómo puedo enfocarlo nuevamente, dado que se especifica en la HU01 que se desea resolver las incompatibilidades horarias, y esto, como he dicho previamente, se realiza más adelante. Entiendo que el problema principal es que se cursen en un mismo día y durante el mismo intervalo horario dos o más asignaturas en las que un estudiante está matriculado, pero ¿qué debería plasmar exactamente para no hacerlo tampoco muy complejo y no salirme del hito?

2023-11-04 12:07 UTC, johnwaves commented on src/horario.ts
> +    private asignaturas: Asignatura[];
Es cierto que por hora no se necesita una clase, aunque más adelante sí que se podría plantear como una.

2023-11-04 12:08 UTC, johnwaves commented on src/estudiante.ts
> +    private asignaturasMatriculadas: Asignatura[];
Asignaturas matriculadas, puesto que no se menciona el hecho de escoger nuevas asignaturas para matricularse en ellas.

2023-11-04 12:46 UTC, JJ commented on src/estudiante.ts
> +    private asignaturasMatriculadas: Asignatura[];
En código limpio y domain driven design es importante que el código explique claramente su función.

2023-11-04 12:48 UTC, JJ commented
> Llegados a este punto, no sé cómo puedo enfocarlo nuevamente, dado que se especifica en la HU01 que se desea resolver las incompatibilidades horarias, y esto, como he dicho previamente, se realiza más adelante. Entiendo que el problema principal es que se cursen en un mismo día y durante el mismo intervalo horario dos o más asignaturas en las que un estudiante está matriculado, pero ¿qué debería plasmar exactamente para no hacerlo tampoco muy complejo y no salirme del hito?

¿Te parece que este sería un buen issue para resolver? Has llegado al quid del asunto: desarrollar es precisamente hacerse esas preguntas y tratar de programar el código, en este caso el modelo, que las resuelve.

2023-11-04 12:55 UTC, johnwaves commented
> > Llegados a este punto, no sé cómo puedo enfocarlo nuevamente, dado que se especifica en la HU01 que se desea resolver las incompatibilidades horarias, y esto, como he dicho previamente, se realiza más adelante. Entiendo que el problema principal es que se cursen en un mismo día y durante el mismo intervalo horario dos o más asignaturas en las que un estudiante está matriculado, pero ¿qué debería plasmar exactamente para no hacerlo tampoco muy complejo y no salirme del hito?
> 
> ¿Te parece que este sería un buen issue para resolver? Has llegado al quid del asunto: desarrollar es precisamente hacerse esas preguntas y tratar de programar el código, en este caso el modelo, que las resuelve.

Sí, me parece que es un issue que se puede resolver aunque podría resultar complejo no explayarse mucho. ¿Sería suficiente solo con un issue si este engloba todo lo necesario?

2023-11-04 13:03 UTC, JJ commented
> > > Llegados a este punto, no sé cómo puedo enfocarlo nuevamente, dado que se especifica en la HU01 que se desea resolver las incompatibilidades horarias, y esto, como he dicho previamente, se realiza más adelante. Entiendo que el problema principal es que se cursen en un mismo día y durante el mismo intervalo horario dos o más asignaturas en las que un estudiante está matriculado, pero ¿qué debería plasmar exactamente para no hacerlo tampoco muy complejo y no salirme del hito?
> > 
> > 
> > ¿Te parece que este sería un buen issue para resolver? Has llegado al quid del asunto: desarrollar es precisamente hacerse esas preguntas y tratar de programar el código, en este caso el modelo, que las resuelve.
> 
> Sí, me parece que es un issue que se puede resolver aunque podría resultar complejo no explayarse mucho. ¿Sería suficiente solo con un issue si este engloba todo lo necesario?

Eso tendrás que verlo tú mirando al issue y si puedes o no resolverlo.

Es que tenéis que entender que este objetivo (y, si me apuras, la asignatura), no van de "hago esto que me piden, issues, código, milestones". Van de que aprendáis a resolver problemas usando metodologías que generalmente están aceptadas en la industria, y que conozcáis y apliquéis esas metodologías. Si *un* issue te ayuda a crear el modelo (que es de lo que va este milestone), usas las buenas prácticas para documentar en los mensajes de commit el mismo y las buenas prácticas del lenguaje en el código creado, si. Si no, pues no.

2023-11-05 16:23 UTC, johnwaves commented
> Es que tenéis que entender que este objetivo (y, si me apuras, la asignatura), no van de "hago esto que me piden, issues, código, milestones". Van de que aprendáis a resolver problemas usando metodologías que generalmente están aceptadas en la industria, y que conozcáis y apliquéis esas metodologías. Si _un_ issue te ayuda a crear el modelo (que es de lo que va este milestone), usas las buenas prácticas para documentar en los mensajes de commit el mismo y las buenas prácticas del lenguaje en el código creado, si. Si no, pues no.

He seguido nuevamente lo que ha propuesto. Esta vez el issue, desde mi punto de vista, engloba todo el problema a resolver y he intentado también seguir las mejores prácticas en cuanto a los mensajes de commit. Esperaré a que @migueruiz lo revise y le mencionaré para que lo haga usted después.

2023-11-06 18:34 UTC, migueruiz approved these changes
Lista de comprobación para el propietario/a del repositorio:

* [x] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [x] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [x] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [x] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [x] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [x] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?

@johnwaves Perdona por la tardanza, no me había avisado github, ni el correo de que me pediste una revisión, yo lo veo correcto, muchas gracias y disculpa. 😄

2023-11-06 19:06 UTC, johnwaves commented
> Lista de comprobación para el propietario/a del repositorio:
> 
> * [x]  ¿Los issues que ha planteado la persona son efectivamente problemas y
>   evidencian comprensión de las historias de usuario? Si no es así, es mejor que
>   se le transmita antes de que empiece a crear cualquier código erróneo.
> * [x]  ¿Has comprobado que efectivamente el compañero/a ha seguido _su_ lista de
>   comprobación?
> * [x]  ¿El código creado es una modelización válida de las historias de usuario
>   creadas por ti, y te sirve como base para programar la lógica de negocio?
> * [x]  ¿El código creado sigue las mejores prácticas para el lenguaje de
>   programación que hayáis consensuado, tanto en identificadores, como
>   nombres de ficheros, como disposición de los diferentes ficheros en el
>   repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
>   aportan código para resolver el problema planteado en el mismo?
> * [x]  ¿He comprobado que el código compile, o que quien lo ha programado ha lo
>   ha hecho y documentado en el repositorio?
> * [x]  ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
>   correspondiente, que será el primero?
> * [x]  ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
>   el objetivo 4 para poder programar la lógica de negocio?
> 
> @johnwaves Perdona por la tardanza, no me había avisado github, ni el correo de que me pediste una revisión, yo lo veo correcto, muchas gracias y disculpa. 😄

No te preocupes. @JJ listo para revisión!

2023-11-07 08:06 UTC, JJ reviewed
Gracias por mejorar el PR, creo que ahora estás un poco más cerca, pero todavía hay algunos problemas de detalle (aparte de los no resueltos), que convendría que resolvieras. También te recuerdo [lo que te comenté la última vez](https://github.com/migueruiz/Automatricula/pull/11#pullrequestreview-1711131072), que no he visto del todo resuelto en esta.

2023-11-07 08:06 UTC, JJ commented on src/asignatura.ts
> +export class Asignatura{
Tampoco lo has resuelto

2023-11-07 08:06 UTC, JJ commented on src/curso.ts
> +    // Los grupos se diferencian entre sí por el horario de las asignaturas.
Si se diferencian entre sí por el horario de las asignaturas, ¿por qué en los atributos figura `asignaturas` y no horarios?
También: la documentación de cualquier código debe ir en el mensaje de commit, y el problema que se plantea en el issue.

2023-11-07 08:06 UTC, JJ commented on src/asignatura.ts
> +export type HoraMinutos = [number, number];
¿No hay ningún tipo específico para esto en TypeScript? Si no lo hay, ¿`number` es la mejor forma de representar un número entero entre 0 y 23?

2023-11-07 08:13 UTC, JJ commented
> Haciendo el recuento de lo que ya hay hecho:
> 
>     1. La matriculación, entendiéndose como elección de asignaturas nuevas, no se contempla en las historias de usuario. El usuario parte desde el punto en el que ya tiene unas asignaturas matriculadas y lo que desea es cambiar de grupo en caso de solapamiento de horarios.

OK, entiendo que esto es `Horario`. En ese caso, ¿cómo reflejas la asignatura de la que querría cambiar de grupo? En HU1 #3 parece que se entiende que sería la asignatura "suelta" la que tendría que cambiar de grupo, porque no se va a cambiar de grupo para todo el curso de segundo. ¿Cómo lo reflejas en esa estructura de datos?
> 
>     2. En primer lugar, y según [[HU01] Alumno Antonio #3](https://github.com/migueruiz/Automatricula/issues/3), la lógica de negocio contempla la visualización del horario conjunto de todas las asignaturas. Una vez obtenido, debería proponer una alternativa en caso de solapamiento de asignaturas.

Visualización no es lógica de negocio, pero ¿dónde propones la alternativa en el modelo? Entiendo que lo que tendría que proponer es un cambio de grupo en una sola asignatura "suelta". ¿Dónde marcas en el modelo esa asignatura y el grupo en el que está?
> 
>     3. La alternativa del punto anterior se deberá tratar como lógica de negocio a seguir en el milestone 2.
> 
> 
> Llegados a este punto, no sé cómo puedo enfocarlo nuevamente, dado que se especifica en la HU01 que se desea resolver las incompatibilidades horarias, y esto, como he dicho previamente, se realiza más adelante. Entiendo que el problema principal es que se cursen en un mismo día y durante el mismo intervalo horario dos o más asignaturas en las que un estudiante está matriculado, pero ¿qué debería plasmar exactamente para no hacerlo tampoco muy complejo y no salirme del hito?

2023-11-07 09:28 UTC, johnwaves commented on src/horario.ts
> +    asignaturas_matriculadas: Asignatura[];
Por ahora no necesita nada más, y creo que podría añadir un atributo `horario` en la clase Estudiante, y de esta forma no sería necesario tener un struct con un solo atributo 🤔.

2023-11-07 09:28 UTC, johnwaves commented on src/estudiante.ts
> +    private asignaturasMatriculadas: Asignatura[];
Lo que entiendo de la HU es que el estudiante ya trae una serie de asignaturas matriculadas previamente. Ahora se le debe proponer únicamente qué asignaturas escoger en caso de solapamiento, es decir, una alternativa al horario actual. Lo que pasa es que si no encuentra una alternativa, o bien la alternativa resuelve un solapamiento y produce otro a su vez, creo que no debería plantearse siquiera. Pero esto es una suposición que hago, ya que este dato no aparece en las HU.

2023-11-07 09:28 UTC, johnwaves commented on src/horario.ts
> +function generaHorario(asignaturas: Asignatura[]): Asignatura[]{
No... Y resulta redundante 😕.

2023-11-07 09:28 UTC, johnwaves commented on src/curso.ts
> +    // Los grupos se diferencian entre sí por el horario de las asignaturas.
Los grupos se diferencian entre sí por la colección de asignaturas que contienen, donde cada asignatura tiene su propio horario. Y como una serie de asignaturas pertenece a un curso, estas se encuentran repetidas en todos los grupos del curso, con la diferencia de que cada una se cursa en horas diferentes, por eso en el atributo figura `asignaturas`.

2023-11-07 09:38 UTC, JJ commented on src/estudiante.ts
> +    private asignaturasMatriculadas: Asignatura[];
Lo que yo entiendo de las HU, corrígeme @migueruiz si me equivoco, es que hay como un curso "principal" en el que ya se está matriculado, y una sola asignatura de otro curso, en la que tienes que buscar el grupo correcto. En ese sentido, quizás habría que distinguir entre unas y otra, creo yo, y eso se debería plantear en el issue correspondiente.

2023-11-07 09:40 UTC, JJ commented on src/horario.ts
> +function generaHorario(asignaturas: Asignatura[]): Asignatura[]{
Como os he comentado, debéis intentar usar los mensajes de commit para explicar por qué habéis hecho esto; en concreto en este caso, por qué habéis decidido incluir una función en el modelo y por qué devuelve un array de asignaturas, por ejemplo, o el horario de qué genera. ¿De las asignaturas en las que está matriculado? ¿En las que se debería matricular?

2023-11-07 09:41 UTC, JJ commented on src/curso.ts
> +    // Los grupos se diferencian entre sí por el horario de las asignaturas.
Si a la lógica de negocio lo que le interesa son los horarios, ¿qué sería más lógico entonces?

2023-11-07 09:42 UTC, JJ commented on src/asignatura.ts
> +export type HoraMinutos = [number, number];
Como siempre, [StackOverflow es tu amigo](https://stackoverflow.com/q/61476095)
Esa decisión, por cierto, es el tipo de cosas que se documentan en el mensaje de commit.

2023-11-07 09:44 UTC, johnwaves commented
> > Haciendo el recuento de lo que ya hay hecho:
> > ```
> > 1. La matriculación, entendiéndose como elección de asignaturas nuevas, no se contempla en las historias de usuario. El usuario parte desde el punto en el que ya tiene unas asignaturas matriculadas y lo que desea es cambiar de grupo en caso de solapamiento de horarios.
> > ```
> 
> OK, entiendo que esto es `Horario`. En ese caso, ¿cómo reflejas la asignatura de la que querría cambiar de grupo? En HU1 #3 parece que se entiende que sería la asignatura "suelta" la que tendría que cambiar de grupo, porque no se va a cambiar de grupo para todo el curso de segundo. ¿Cómo lo reflejas en esa estructura de datos?
> 
> > ```
> > 2. En primer lugar, y según [[HU01] Alumno Antonio #3](https://github.com/migueruiz/Automatricula/issues/3), la lógica de negocio contempla la visualización del horario conjunto de todas las asignaturas. Una vez obtenido, debería proponer una alternativa en caso de solapamiento de asignaturas.
> > ```
> 
> Visualización no es lógica de negocio, pero ¿dónde propones la alternativa en el modelo? Entiendo que lo que tendría que proponer es un cambio de grupo en una sola asignatura "suelta". ¿Dónde marcas en el modelo esa asignatura y el grupo en el que está?

Creo que, en todo caso, debería indicar las asignaturas con problemas y las propuestas en la clase `Estudiante`.

2023-11-07 09:59 UTC, migueruiz commented on src/estudiante.ts
> +    private asignaturasMatriculadas: Asignatura[];
Lo que me refiero en las HU, es el caso en el que yo estoy matriculado de una serie de asignaturas, que pertenecen a un grupo en específico, y me tengo que matricular de una o varias asignaturas de otro año, que quizás se solapan o no con el horario "principal" por así decirlo, le doy cierta prioridad al grupo en el que me he matriculado del curso mayoritario (es decir si tengo más asignaturas de 3º de carrera, pues que no me ofrezca cambios para esas, sino para las de otros cursos en el caso de que hubiese más opciones), ya que sino, el programa no sabría bien como valorar que asignatura me debe de ofrecer un cambio o no. No se si se me entiende.

2023-11-07 11:08 UTC, JJ commented on src/estudiante.ts
> +    private asignaturasMatriculadas: Asignatura[];
¿En qué issue has especificado esto? ¿Cómo lo has reflejado en el código? ¿En qué mensaje de commit lo has aclarado?

2023-11-07 13:10 UTC, migueruiz commented on src/estudiante.ts
> +    private asignaturasMatriculadas: Asignatura[];
¿Se refiere a mi @JJ o al compañero @johnwaves?

2023-11-07 14:17 UTC, JJ commented on src/estudiante.ts
> +    private asignaturasMatriculadas: Asignatura[];
En este caso a @johnwaves. La HU la veo bastante clara, no hace falta mucho más.

2023-11-07 14:23 UTC, johnwaves commented on src/estudiante.ts
> +    private asignaturasMatriculadas: Asignatura[];
> En este caso a @johnwaves. La HU la veo bastante clara, no hace falta mucho más.

Tendré en cuenta lo que acaba de aclarar @migueruiz.

2023-11-10 13:03 UTC, johnwaves commented on src/types.ts
> +        nombre: string;
Resuelto en [110159d](https://github.com/migueruiz/Automatricula/pull/11/commits/110159d3b22ea136bb10f1dc6faef53341808ca2).

2023-11-10 13:04 UTC, johnwaves commented on src/asignatura.ts
> + * Clase Asignatura.
Resuelto en [5905d29](https://github.com/migueruiz/Automatricula/pull/11/commits/5905d293b6e757ef8faee77b6103a77a4fe74901).

2023-11-10 13:05 UTC, johnwaves commented on src/asignatura.ts
> +export class Asignatura{
Resuelto en [5905d29](https://github.com/migueruiz/Automatricula/pull/11/commits/5905d293b6e757ef8faee77b6103a77a4fe74901).

2023-11-10 13:06 UTC, johnwaves commented on src/estudiante.ts
> +    private asignaturasMatriculadas: Asignatura[];
Resuetlo en [cf4ecb2](https://github.com/migueruiz/Automatricula/pull/11/commits/cf4ecb256c683b765411f059a8ee17b9b6b123d5).

2023-11-10 13:07 UTC, johnwaves commented on src/horario.ts
> +function generaHorario(asignaturas: Asignatura[]): Asignatura[]{
Se eliminó esta función en [7d99a5e](https://github.com/migueruiz/Automatricula/pull/11/commits/7d99a5e15921d58b209641c4890ac7829ed028c0).

2023-11-10 13:09 UTC, johnwaves commented on src/horario.ts
> +    asignaturas_matriculadas: Asignatura[];
Se ha resuelto de otra forma, la cual se comenta en [62a42d2](https://github.com/migueruiz/Automatricula/pull/11/commits/62a42d2233f56ff9fc5e6df5a9d28941ccbf7968).

2023-11-10 13:11 UTC, johnwaves commented on src/curso.ts
> +    // Los grupos se diferencian entre sí por el horario de las asignaturas.
Se resuelve en [110159d](https://github.com/migueruiz/Automatricula/pull/11/commits/110159d3b22ea136bb10f1dc6faef53341808ca2), [aa75c95](https://github.com/migueruiz/Automatricula/pull/11/commits/aa75c959416c0ee2acb4231f11bbabe7ede30940) y [ea7a5a7](https://github.com/migueruiz/Automatricula/pull/11/commits/ea7a5a75a839c86d1e750f23f6964bbb7e70f8a8).

2023-11-10 13:29 UTC, JJ approved these changes
👍 pero por favor, usa nombres significativos en las variables y *siempre el mismo*. Asignatura tiene que ser Asignatura siempre.

2023-11-13 08:43 UTC, merged