[IV-23-24] Objetivo 1. Planificación del proyecto
migueruiz/Automatricula pull request #2
Opened 2023-09-26 16:09 UTC by migueruiz

## Milestones

* [ ] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [ ] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [ ] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [ ] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [ ] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [ ] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [ ] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [ ] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [ ] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [ ] ¿El milestone 0 es mínimo *y* viable?
* [ ] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [ ] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

## Historias de usuario

* [ ] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [ ] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [ ] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [ ] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2023-09-26 16:25 UTC, manuelvico0102 commented on doc/milestone.md
> +
Te recomiendo que para cada milestone indiques claramente cual es el objetivo, lo que se espera entregar y lo que lo haría viable

2023-09-26 16:25 UTC, manuelvico0102 commented on doc/historias_usuario.md
> +## [HU03]
Deberías añadir más contexto a las historias de usuario, así como indicar con que datos se trabajaran.

2023-09-28 06:53 UTC, migueruiz commented
@manuelvico0102 Listo para revisión.

2023-09-28 06:55 UTC, migueruiz commented on doc/historias_usuario.md
> +## [HU03]
@manuelvico0102  Lo he resuelto para las historias de usuario que me indicaste.

2023-09-28 06:56 UTC, manuelvico0102 commented
Vale, creo que ya esta listo para que el profesor lo revise. Suerte

2023-09-28 06:56 UTC, manuelvico0102 approved these changes

2023-09-28 16:07 UTC, migueruiz commented
@JJ Listo para revisión, tras la aprobación de mi compañero.

2023-09-29 05:31 UTC, JJ requested changes
El problema principal (sin haber revisado los milestones, que supongo que @manuelvico0102 habrá revisado correctamente) es que el contexto en el que se plantea la HU principal, es decir, hablar del momento en que *ya* ha elegido asignaturas en vez de plantear de forma precisa *cuando* es cuando se puede ayudar al estudiante, no es el correcto. Y como no lo es, no plantea todas las cuestiones relacionadas con el mismo: la posibilidad de elegir grupo de mañana o de tarde, la cantidad de asignaturas en las que se puede matricular uno, algunas otras restricciones (si las hay, que al parecer según hablamos no es el caso). Por favor, piénsate bien las HUs y trata de mejorarlas en el sentido de hacerlas más fáciles de entender para quien vaya a trabajar en ellas.

2023-09-29 05:31 UTC, JJ commented on doc/historias_usuario.md
> +Antonio es un estudiante de universidad que esta cursando 2 pero tiene una asignatura que tiene que repetir de 1, el ya tiene el horario de las clases final que le ha quedado tras las elecciones de a
El problema es que en las HUs de alguna forma tienes que plantear el contexto, el *momento* en que hace falta la solución. Cuando tenga un horario con dos asignaturas que coincidan ya es un poco demasiado tarde. Tampoco plantea exactamente qué quiere y cuando lo quiere. ¿Te podrías plantear pasarlo a un user journey? Recuerda que las historias de usuario plantean situaciones que se tienen que convertir en tests; como tal, esto podría servir (simplemente testear que no suceda), pero no hace una referencia a un contexto un poco más amplio.

2023-09-29 05:31 UTC, JJ commented on doc/historias_usuario.md
> +Laura es una estudiante de ultimo año de carrera. Le quedan solo tres asignaturas para terminar la carrera de diferentes cursos, pero tiene un problema con las horas de las asignaturas que quiere cur
Deberías tratar de extender un poco más el contexto. Aquí entiendo que se trata de pocas asignaturas, pero hay que hacerlas todas. Sin embargo, no planteas qué exactamente es el problema. ¿Dejar alguna asignatura?

2023-09-29 05:31 UTC, JJ commented on doc/historias_usuario.md
> +Manuel es un estudiante de primer año de carrera, él al no tener ninguna asignatura de otro curso que tenga que repetir, ya que no ha cursado nada aún, solo tiene la posibilidad de elegir un grupo co
Si no tiene problemas, no es una historia de usuario. Puede ser un issue.

2023-09-29 07:38 UTC, migueruiz commented
@JJ Listo para la revisión.

2023-09-29 07:45 UTC, JJ requested changes
Tratad de ser un poco más precisos en la descripción de los milestones.

2023-09-29 07:45 UTC, JJ commented on doc/milestone.md
> +[M2] **Implementación de una función que a partir del horario que ha seleccionado el alumno, compruebe si hay incompatibilidades horarias entre las asignaturas que ha seleccionado.**
Por favor, no pongáis "una función". Puede ser una o pueden ser 25. Referiros exactamente a lo que hay que hacer: implementar la lógica de negocio a partir del m0 que es el modelo del problema.

2023-09-29 07:49 UTC, migueruiz commented
@JJ Listo para la revisión.

2023-09-29 07:54 UTC, JJ approved these changes
👍

2023-09-29 07:59 UTC, merged