[IV-23-24] Objetivo 4
migueruiz/Automatricula pull request #34
Opened 2023-11-17 08:59 UTC by migueruiz

* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [ ]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ] ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por
delante?
* [ ] ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [ ] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [ ] ¿Se han testeado también las excepciones?

2023-11-22 07:46 UTC, JJ commented
Arregla el YAML, por favor.
Espero a que alguien te lo corrija; si no lo hace nadie el viernes me avisas.

2023-11-22 08:17 UTC, migueruiz commented
@JJ Arreglado. A esperar que algún compañero me diga algo, y si no le avisare a usted. 😄

2023-11-22 09:02 UTC, migueruiz commented
@manuelvico0102 Ya he resuelto lo que me has comentado! Si tienes alguna objeción más, no dudes en comentármela! 😄

2023-11-22 09:09 UTC, manuelvico0102 reviewed
A parte de lo que te he mencionado creo que ya todo está bien. Por lo que @JJ ya puede pasar a revisarte. Suerte.

2023-11-22 09:09 UTC, manuelvico0102 commented on doc/herramientas_test.md
> +- [Should](https://www.npmjs.com/package/should): Should es una biblioteca de aserciones para Node.js, compatible con TypeScript. Tiene una valoración de [61](https://snyk.io/advisor/npm-package/shou
Si es una biblioteca que ya no tiene mantenimiento es mejor ni mencionarla y buscar otras opciones.

2023-11-22 09:09 UTC, manuelvico0102 approved these changes

2023-11-22 09:10 UTC, migueruiz commented
@JJ Listo para revisión!

2023-11-22 09:22 UTC, JJ requested changes
Antes de ver cómo has aplicado efectivamente la lógica de negocio, deberías revisar un poco el código para que siga las buenas prácticas.

2023-11-22 09:22 UTC, JJ commented on doc/herramientas_test.md
> +- [Should](https://www.npmjs.com/package/should): Should es una biblioteca de aserciones para Node.js, compatible con TypeScript. Tiene una valoración de [61](https://snyk.io/advisor/npm-package/shou
Con 61, ni la pongas.

2023-11-22 09:22 UTC, JJ commented on doc/herramientas_test.md
> +- [Supertest](https://www.npmjs.com/package/supertest): Supertest es un test runner para Node.js. Sin embargo, no es compatible con Typescript. Por lo que no nos sirve, a pesar de que su valoración e
supertest es para testear servicios web y cosas así. NO creo que deba estar aquí.

2023-11-22 09:22 UTC, JJ commented on doc/herramientas_test.md
> +- [AVA](https://github.com/avajs/ava): AVA es un test runner con soporte para TypeScript. Una gran ventaja es que cuenta con una biblioteca de aserciones integrada pero el problema que nos surge es q
Ava soporta todo, es un test runner puro que ejecuta tests y punto. Si mal no recuerdo, la biblioteca que tiene ava es muy escasa y sólo sirve para hacer un mínimo complemento a alguna biblioteca de aserciones.

2023-11-22 09:22 UTC, JJ commented on package.json
>          "typescript": "^5.2.2"
Si no lo vas a usar en producción, esto no tiene que estar aquí.

2023-11-22 09:22 UTC, JJ commented on package.json
>          "start": "node dist/estudiante.ts"
??

2023-11-22 09:22 UTC, JJ commented on src/estudiante.ts
> +                    comprobadoHorario = this.comprobarHora(asigGrup.grupo.horario[0][1][0][0], asigGrup2.grupo.horario[0][1][0][0], asigGrup.grupo.horario[0][1][0][1], asigGrup2.grupo.horario[0][1][0
¿Seguro que no hay una forma un poco más simple de hacer esto? ¿Te parece que usar esos índices es limpio y/o cómodo?

2023-11-22 09:22 UTC, JJ commented on src/estudiante.ts
> +                    comprobadoHorario = this.comprobarHora(asigGrup.grupo.horario[0][1][0][0], asigGrup2.grupo.horario[0][1][0][0], asigGrup.grupo.horario[0][1][0][1], asigGrup2.grupo.horario[0][1][0
Si lo que le estás pasando son fechas, DDD y código limpio dice que hay que usar los tipos de datos (y nombres de variables) que sean más apropiados. Usar arrays, y más tan complicados, sólo complica la lectura del código. Además, ¿Matrices cuatridimensionales?

2023-11-22 09:30 UTC, migueruiz commented on package.json
>          "typescript": "^5.2.2"
De acuerdo, lo cambiaré entonces.

2023-11-22 09:32 UTC, migueruiz commented on package.json
>          "start": "node dist/estudiante.ts"
Para la ejecucion de los test, si pongo en la terminal npm run test, me ejecuta ese script, que lo hace es empezar los tests, no si si quizas no se deba de hacer de esta manera.

2023-11-22 09:33 UTC, migueruiz commented on src/estudiante.ts
> +                    comprobadoHorario = this.comprobarHora(asigGrup.grupo.horario[0][1][0][0], asigGrup2.grupo.horario[0][1][0][0], asigGrup.grupo.horario[0][1][0][1], asigGrup2.grupo.horario[0][1][0
De acuerdo cambiaré los indices, añadiendo otras funciones que me ayuden a solucionar esto! 😄

2023-11-22 09:34 UTC, migueruiz commented on src/estudiante.ts
> +                    comprobadoHorario = this.comprobarHora(asigGrup.grupo.horario[0][1][0][0], asigGrup2.grupo.horario[0][1][0][0], asigGrup.grupo.horario[0][1][0][1], asigGrup2.grupo.horario[0][1][0
De acuerdo, cambiaré el contenido, para que todo quede más legible!
Las matrices de cuatro dimensiones, son porque para poder acceder a la hora de inicio según la estructura que me dejo mi compañero debo de acceder así, lo cambiaré por funciones para que quede más legible! Gracias por sus apuntes! 😄

2023-11-22 09:48 UTC, migueruiz commented
He cambiado el resto de cosas, pero estoy a la espera, que me diga algo sobre el único comentario que no he resuelto @JJ. Cuando pueda me comenta y ya continuo con el trabajo. :smile:

2023-11-23 08:07 UTC, JJ requested changes
Trata de reorganizar el código para no usar matrices cuatridimensionales; trata de crear casos de uso más completos, y también avanzar un poquito más en la lógica de negocio.

2023-11-23 08:58 UTC, migueruiz commented
Listo para revisión @JJ. 😄

2023-11-23 09:10 UTC, JJ approved these changes
👍 
Salvo lo comentado

2023-11-23 09:20 UTC, merged