[IV-23-24] Objetivo 5
migueruiz/Automatricula pull request #41
Opened 2023-11-24 11:37 UTC by migueruiz

2023-11-26 17:42 UTC, javigp2002 reviewed
Muy buen objetivo :100: y se de buena mano que has trabajado, sin embargo, te he dejado algunos apuntes. Buen trabajo con los enlaces de **docker** y **snyk** así como el criterio de emplear este último. Por otro lado, el `dockerfile` si es lo que estuviste trabajando con JJ está bien y supongo que ha sido imposible utilizar el user genérico para poder ejecutar los json.

2023-11-26 17:42 UTC, javigp2002 commented on doc/eleccion_imagen_base.md
> +- **Compatibilidad**: La imagen base debe de ser compatible con el proyecto que vamos a realizar, y con todas las herramientas que necesitamos para su despliegue posterior.
En todas las imágenes base mencionas snyk pero no se considera un criterio de decisión. Deberías mencionarlo si ves que es importante de cara a la elección.

2023-11-26 17:42 UTC, javigp2002 commented on dockerfile
> +LABEL maintainer="mruiz812@correo.ugr.es"
Hay otra `label` que sigue las buenas prácticas de un dockerfile, deberías echar un vistazo sobre cómo poder especificar las versiones que vas a ejecutar.

2023-11-28 09:20 UTC, migueruiz commented
@JJ Listo para revisión! 😄

2023-11-28 10:37 UTC, JJ requested changes
Aparte de lo comentado, si buscas nodejs en las imágenes de Docker Hub, ¿hay alguna imagen más que pueda usarse? ¿Puede ser interesante en cuanto a tamaño, por ejemplo?

2023-11-28 10:37 UTC, JJ commented on doc/eleccion_imagen_base.md
> +- **Tamaño optimo**: Es conveniente que la imagen base sea lo más pequeña posible para que el container sea lo más ligero posible.
typo

2023-11-28 10:37 UTC, JJ commented on doc/eleccion_imagen_base.md
> +* [cimg/node](https://hub.docker.com/r/cimg/node): es una imagen de node basada en debian, su tamaño es de 1.32GB por lo que no se considera una opción muy favorable, a pesar de ello cuenta con una b
Tiene [versiones de tamaños bastante inferiores](https://hub.docker.com/r/cimg/node/tags)
Es también una versión de Circle CI. Así que como os dije, dependiendo de lo que se vaya a escoger para el objetivo 6 podría ser conveniente, simplemente por cercanía.

2023-11-28 10:37 UTC, JJ commented on doc/eleccion_imagen_base.md
> +Tras valorar las diferentes opciones que he encontrado, me decantare por la imagen oficial de node, pero la variante de Alpine, ya que es una imagen muchisimo más ligera, y que además cumple con el r
¿Has mirado [lo que dice Snyk Advisor](https://snyk.io/advisor/docker/node)?

2023-11-28 10:37 UTC, JJ commented on dockerfile
> +RUN npm ci
Después de esta orden, ¿hace falta que estén ahí esos dos ficheros?

2023-11-28 10:37 UTC, JJ commented on dockerfile
> +RUN mkdir /.npm && chmod 777 /.npm
¿Seguro que necesitas esto al final?

2023-11-28 10:47 UTC, migueruiz commented on dockerfile
> +RUN mkdir /.npm && chmod 777 /.npm
Si no hago ese comando, los tests siguen pasandose, pero me aparecen errores de que no pueden acceder a la información correctamente, algo diferente parecido que nos pasaba el viernes en la clase.

2023-11-28 10:47 UTC, migueruiz commented on dockerfile
> +RUN npm ci
Si no hago eso, no me deja crear la imagen de docker, me presenta errores

2023-11-28 10:48 UTC, migueruiz commented on doc/eleccion_imagen_base.md
> +Tras valorar las diferentes opciones que he encontrado, me decantare por la imagen oficial de node, pero la variante de Alpine, ya que es una imagen muchisimo más ligera, y que además cumple con el r
Según snyk advisor, la imagen de alpine es más pequeña que la de alpine, por ende he elegido esa, además de que no esta mal valorada.

2023-11-28 10:49 UTC, migueruiz commented on doc/eleccion_imagen_base.md
> +- **Tamaño optimo**: Es conveniente que la imagen base sea lo más pequeña posible para que el container sea lo más ligero posible.
Buscare más opciones para ver las diferentes opciones que puedo tener.

2023-11-28 11:03 UTC, migueruiz commented
@JJ He cambiado lo que he podido, si encuentra algún otro error comentemelo, con gusto lo arreglaré lo mas rápido que pueda.

2023-11-28 13:03 UTC, JJ requested changes
Abrir issues tiene su razón de ser, y ligarlos al código también: así sabes perfectamente la razón por la que has creado un código determinado y qué soluciona. Y cuando la razón de ser de ese código desaparece, puedes pasar muy fácilmente a eliminar todo el código que no sea necesario. Traducido: mira de verdad esa línea en el `dockerfile` a ver si la necesitas. Porque es posible que la necesites, pero también es posible que puedas decir por algún lado que escriba ese fichero en otro directorio donde sí tengas permiso.

Los cambios al código, salvo los estrictamente necesarios para cambiar la elección del framework de test, debes considerar si caben en este PR que, recuerda, es sólo para el objetivo 5.

Finalmente hay un problema sutil con tu imagen que posiblemente no has detectado:

```text
podman image tree jjmerelo/migue-test
Image ID: 3bc488a00bab
Tags:     [localhost/jjmerelo/migue-test:latest]
Size:     229.6MB
Image Layers
├── ID: cc2447e1835a Size: 7.626MB
├── ID: 8bf632eb5969 Size: 129.2MB
├── ID: 15cca29fd2a7 Size: 7.855MB
├── ID: c82b2e2ffd36 Size: 3.584kB Top Layer of: [docker.io/library/node:21-alpine]
├── ID: f8a25d0d423d Size: 3.584kB
├── ID: cace2264ae19 Size: 2.048kB
├── ID: 31921507cd2d Size: 301.1kB
└── ID: 98b79b971acc Size: 84.59MB Top Layer of: [localhost/jjmerelo/migue-test:latest]
```

Como ves, tu última capa son 84 megas, lo que lleva el total a más de 200 megas. Puede ser que en tu `package-lock.json` todavía queden restos del `vitest` anterior.

2023-11-28 13:19 UTC, migueruiz commented
@JJ De acuerdo, intentaré cambiarlo lo más pronto posible, muchas gracias por sus comentarios!! 🫡

2023-11-28 14:50 UTC, migueruiz commented on src/types.ts
> +    horario: Date[][];
Me he confundido al escribir el código, nos quedamos con matrices unidimensionales.

2023-11-28 15:13 UTC, migueruiz commented on dockerfile
> +RUN mkdir /.npm && chmod 777 /.npm
Pasaba con vitest y  con jest, si utilizo esa línea no me muestra ningún error, ya no se que más poder hacer, porque estoy en la misma rueda que el otro día en clase, la única solución para que no salga el error, es dejar esa línea. Esperare su respuesta, pero pinta feo el poder arreglar este problema de otra manera.

2023-11-28 16:18 UTC, migueruiz commented on dockerfile
> +RUN mkdir /.npm && chmod 777 /.npm
He estado mirando desde que le comente, y no encuentro otra solución posible @JJ, ya lo único que me queda es hacer un conjuro y que me aparezca de la nada. He borrado la imagen, la he vuelto a crear, he borrado npm, he borrado jest, vitest, todo, lo he vuelto a instalar, cambiando las dependencias, cambiando todo. No se que más hacer estoy desesperado. Si usted lo ha encontrado o cualquier cosa, se lo agradecería muchísimo que me lo pasase, y sino, pues ya no se que más poder hacer...

2023-11-28 16:19 UTC, JJ commented on test/comprobar_horario.test.ts
> -            dia : "Miércoles" as Dia,
Qué va, ¿por qué? Estas haciendo un "casting" o cambio de tipo de string ("Miércoles") a `Dia`. Es puro Typescript.

2023-11-28 16:40 UTC, migueruiz commented on test/comprobar_horario.test.ts
> -            dia : "Miércoles" as Dia,
Vale si lo acabo de cambiar, ya es que como le he comentado, me daban tantos errores por todos lados, que cambiaba todo, para que no me presentara errores... disculpe por ser así...

2023-11-28 16:41 UTC, JJ commented on test/comprobar_horario.test.ts
> -            dia : "Miércoles" as Dia,
Disculpa ninguna, pero aprended a abrir issues cuando se produzcan errores y a ir solucionándolos de uno en uno, os irá mejor...

2023-11-29 09:31 UTC, migueruiz commented
Buenos días @JJ ¿Que hago, me espero a mañana en clase, o le entrego con la solución que tenía anteriormente en el dockerfile? Perdón por la insistencia, pero es que me encuentro muy perdido 😅

2023-11-29 09:35 UTC, JJ requested changes
Dale una vueltecilla a las cosas pendientes que hay. Resuelve lo de la línea con `.npm` y mañana te cuento.

2023-11-29 09:35 UTC, JJ commented on dockerfile
> +RUN mkdir /.npm && chmod 777 /.npm
Sí, he encontrado el problema. Mañana lo hablamos. Creo que por lo pronto lo voy a dejar pasar.

2023-11-29 09:35 UTC, JJ commented on dockerfile
> +RUN npm ci
No te estoy diciendo eso, sino si necesitas que sigan ahí. Piensa que esos ficheros van a estar en /app/test cuando testees.

2023-11-29 09:35 UTC, JJ commented on package.json
>          "typescript": "^5.2.2"
Esto sigue siendo una dependencia de desarrollo.

2023-11-29 09:38 UTC, migueruiz commented on dockerfile
> +RUN npm ci
Ah vale de acuerdo, había entendido si necesita tener los archivos, de acuerdo, lo cambio entonces.

2023-11-29 10:00 UTC, migueruiz commented
@JJ Listo para revisión! 😄. Todo lo que me has comentado arreglado, si encuentra otro error más, agradecería que me lo dijese, muchas gracias y disculpe por las molestias.

2023-11-29 10:06 UTC, JJ approved these changes
:+1:

2023-11-29 10:06 UTC, JJ commented on dockerfile
> +RUN rm -rf package.json package-lock.json
La `-r` es borrado recursivo de directorios. Aquí no lo necesitas.

2023-11-29 10:11 UTC, merged