[IV-23-24] Objetivo 6
migueruiz/Automatricula pull request #49
Opened 2023-11-30 12:49 UTC by migueruiz

* [x] ¿Se han establecido criterios *a priori* para elegir el sistema de
integración continua más conveniente y se han calificado los sistemas que
cumplan esos requisitos según esos criterios?
* [x] ¿Se han examinado varios sistemas de integración continua?
* [x] ¿Se han configurado varios sistemas de integración continua?
* [x] ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que
   sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar
   desde los tests)?
* [x] ¿Uno de los sistemas configurados permite comprobar cuales son las versiones
   dellenguaje con las que funciona correctamente nuestra aplicación?
* [x] ¿Se escogen de forma adecuada las versiones del lenguaje que se testean,
   tanto en el sistema de CI como en el contenedor Docker?
* [x] ¿Se han justificado correctamente las versiones del lenguaje que se están
testeando y se ha comprobado que no se comprueban varias veces lo mismo (la
misma versión en CI y en el contenedor Docker en otro sistema CI?

2023-11-30 15:17 UTC, danieeeld2 commented
¿Está para revisar @migueruiz? Como sale en draft.

2023-11-30 15:19 UTC, migueruiz commented
Aún estoy en proceso de terminarlo, cuando termine te aviso 🫡

2023-11-30 16:52 UTC, migueruiz commented
@danieeeld2 Listo para la revisión!

2023-11-30 17:35 UTC, danieeeld2 approved these changes
:+1: En general muy bien, se podría haber intentado probar alguna herramienta más, pero es verdad que la mayoría son complicadas, lo digo por experiencia propia de ayer jajaja. No sé como será para `node`, pero en `go` la verdad que `cirrus` y `circle` eran gemelas. Como todavía no lo ha usado mucha gente no creo que tengas problemas :). Si tuvieras alguno y te pidiese otra, puedes probar `Travis`, hasta hace poco tenía buen soporte, pero ahora han cambiado de equipo y está algo peor (pj en `go` no tenían la última versión, pero creo que para `node` sí)

2023-11-30 17:39 UTC, migueruiz commented
> 👍 En general muy bien, se podría haber intentado probar alguna herramienta más, pero es verdad que la mayoría son complicadas, lo digo por experiencia propia de ayer jajaja. No sé como será para `node`, pero en `go` la verdad que `cirrus` y `circle` eran gemelas. Como todavía no lo ha usado mucha gente no creo que tengas problemas :). Si tuvieras alguno y te pidiese otra, puedes probar `Travis`, hasta hace poco tenía buen soporte, pero ahora han cambiado de equipo y está algo peor (pj en `go` no tenían la última versión, pero creo que para `node` sí)

Muchas gracias por tu review @danieeeld2!!! 😄

2023-11-30 17:39 UTC, migueruiz commented
@JJ Listo para revisión!!

2023-11-30 18:58 UTC, JJ requested changes
Usar una versión fija no acaba de ser buena idea; en todo caso también conviene que contemples otras posibilidades en sistemas de integración continua.

2023-12-01 08:08 UTC, migueruiz commented
@JJ Listo para revisión!!

2023-12-01 08:18 UTC, danieeeld2 commented on doc/eleccion_ci.md
> +* [Buddy](https://buddy.works/)
😲 no había visto este antes

2023-12-01 08:37 UTC, JJ approved these changes
👍

2023-12-01 08:43 UTC, merged